### PR TITLE
Pluggable discovery initial implementation

### PR DESCRIPTION
**Pull request by PaulStoffregen**
Here's an initial implementation for PluggableDiscovery.

The BoardPort class is used for JSON parsing, but other than a copy constructor I have not made any changes to BoardPort yet.

Please accept my apology in advance if this pull request is incorrect or goes to the wrong place.  I'm not an expect with git & github.  This pull request is meant to request adding to @cmaglie pluggable-discovery branch, rather than the main Arduino repository.

### CODE REVIEW

**Comment by facchinm** [comment]
Hi @PaulStoffregen, I pushed your commits to cmaglie/pluggable-discovery so they got added to PR #8038 . Maintainers/collaborators can push to feature branches by just adding the correct remote and pushing to the PR branch :wink:

**Comment by PaulStoffregen** [comment]
Thanks!

**Comment by PaulStoffregen** [comment]
@facchinm - Any chance you could give me a pointer on "just adding the correct remote and pushing to the PR branch"?  I'm not a git expert....

I have a new commit to add the PluggableDiscovery metadata, rather than (mis)using the online field.  But how to push it to that pull request?  (and not accidentally mess up anything else on Arduino's main repository!)

https://github.com/PaulStoffregen/Arduino/commit/07eee5e3743592a35d49f9061addf7d6b0ae6319

**Comment by PaulStoffregen** [comment]
Ok, I think I found a way, using another clone from Cristian's fork.

Someday I ought to invest more time into learning the finer points of git.....

**Comment by facchinm** [comment]
On git you can setup many "remotes" for a single repo, so if you are working on branch `foo` (locally) and want to push to `cmaglie/pluggable-discovery` you need to:
- add @cmaglie 's repo as a remote with `git remote add cmaglie git@github.com:cmaglie/Arduino.git`
- push your branch to his branch with `git push cmaglie foo:pluggable-discovery`

**Pull request closed without merging**
